[package]
name = "aesthetic-prototype"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = "0.25.0"
base64 = "0.22.1"
image = "0.25.4"
imageproc = "0.25.0"
rustface = "0.1.7"
tokio = { version = "1.41.0", features = ["full"] }
