[project]
name = "aesthetic-prototype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepface>=0.0.93",
]

[tool.pyright]
venvPath = "."
venv = ".venv"